### ISSUE TITLE
French dates not supported

### ISSUE THREAD

**Issue by jleclanche** [philipmulcahy/azad#107]
See screenshot:

![image](https://user-images.githubusercontent.com/235410/86071523-c65fc700-ba7f-11ea-87f4-05ebefc73d17.png)

`Commandé le ([day] [month name] [year])` is the format.

**Comment by philipmulcahy** [comment]
This is weird. My fr orders (all one of them - the digital ones appear to be an amazon bug) are showing sensible dates...
![image](https://user-images.githubusercontent.com/1668892/86520882-5798ba00-be41-11ea-9178-1f5b5ac1b7aa.png)
The corresponding order page has a similar format to what's leaking through for you:
![image](https://user-images.githubusercontent.com/1668892/86520963-5e73fc80-be42-11ea-9920-52667033200a.png)
It shows up like this on the order list page:
![image](https://user-images.githubusercontent.com/1668892/86520914-c544e600-be41-11ea-9346-95c01db016cc.png)

Would you mind sending me a dump file from one of your orders please? (right click on the order id link in the azad output table - one of the right click menu items mentions azad and dump - that's the one. If any of the (typically nine) other orders on the same list page is one you don't want me to know about, pick another order! Don't send it to this ticket (because everyone will be able to see it), instead use philip at mylastnamefamily.org
If I can reproduce it, it should be easy to fix. After that, we need to start comparing browser and os localisation settings.

**Comment by philipmulcahy** [comment]
A few days I pushed a shot in the dark attempt at a fix. @jleclanche please test 1.9.8
Yours,
Philip

**Comment by philipmulcahy** [comment]
I’m assuming that fixed it as no response in nearly a month.

**Comment by jleclanche** [comment]
@philipmulcahy Sorry for the radio silence, work has been keeping me away from this project. I still have testing this in my todo. I'll let you know if it's not fixed.
