### ISSUE TITLE
Extension does not work

### ISSUE THREAD

**Issue by merak69** [philipmulcahy/azad#129]
This is the first time I've tried using this and I cannot get it to work.  I've followed the instructions in the readme to clear Amazon site data as well as clearing the cache in the extension.  I even went as far as clearing everything from the browser cache to no avail.

I get a blank table that says: "No data available in table"

In looking at the console there is a javascript error: "settings.ts:84 JSON.parse blew up with: SyntaxError: Unexpected token u in JSON at position 0 while parsing:undefined"

[www.amazon.com-1601928176452.log](https://github.com/philipmulcahy/azad/files/5329832/www.amazon.com-1601928176452.log)

I've attached the console log for your review.  Thanks!

**Comment by itzallan** [comment]
I'm having a problem with the extension also. It was working two weeks ago, but today I can't get it to work for the current year (2020), although it pulls the data for previous years.  For the current year, I get "No data available in table"

In the error page, I get the message "Error: Attempting to use a disconnected port object."

![image](https://user-images.githubusercontent.com/8881966/95139755-1787f280-0722-11eb-981f-4d30d67b4a0a.png)

**Comment by philipmulcahy** [comment]
@itzallan that error is probably not what's causing your problem - can you attach a full console log please?

@merak69 1) I think this might be related to not having set settings (ever) - I thought I'd nailed this bug a few months ago. The workaround (please try and let me know) is to open the control popup, set the checkboxes, close the popup and see if the checkboxes are still set, then set them how you actually want them. What's going on is that the code is blowing up when it attempts to read a settings object that has never been saved.
2) If that doesn't work, try disabling the extension in chrome://settings, enabling developer mode, download this: www.mulcahyfamily.org/azad/azad.afaaa52d.zip, unpack it and then point chrome://extensions at the resulting folder (load unpacked extension), and try it out. If it works, please let me know. Do 1) before 2), because 2) will mess up validity of experiment 1.

**Comment by itzallan** [comment]
@philipmulcahy - I ran the extension today and I was finally able to get it to capture all the data for the current year. At first it only returned one record. After I cleared the cache, unchecked the two checkboxes, and ran it again, it pulled all the current year data. That's interesting because when I was encountering the problem the other day, I had cleared the extension's cache (several times) and cleared all the Amazon cookies, but I still couldn't get it to return the current year data. So at least for now it's back to functioning properly.

**Comment by merak69** [comment]
@philipmulcahy - I followed the steps for #1 you outlined and it did fix the JSON error I had before but the table is still blank.  Should I go ahead with the developer extension path or is something else going on now?  FYI, I cleared the cookies and the cache again after it didn't work the first time and then tried again but the console log shows the same results (attached).  Thanks for looking into this; I'm really excited to be able to use the extension.

[www.amazon.com-1602081591524.log](https://github.com/philipmulcahy/azad/files/5341516/www.amazon.com-1602081591524.log)

**Comment by philipmulcahy** [comment]
I'd give the dev version a go, but if that doesn't work, your most recent log looks a bit like you're partially logged out (except that the extension is supposed to detect and complain about that - I wonder if Amazon is doing something new - I am on notice to do some debugging when it next happens to me.

Fair warning: the logging from the dev version you have the link for is a bit spammy with warnings. I have removed most of them from HEAD.

**Comment by merak69** [comment]
The dev version had a ton of errors in the console log about "no order elements existing" but otherwise, those aside, the results were the same.

[www.amazon.com-1602116553374.log](https://github.com/philipmulcahy/azad/files/5344657/www.amazon.com-1602116553374.log)

**Comment by merak69** [comment]
I spent a bit stepping through JS and when it goes into the util.ts:findMultipleNodeValues() the HTMLElement value on the surface looks right but if you inspect the variable, the divs inside there show some kind of "csd-encrypted-uuid" BS and you can't see anything there.  I could be wrong but I think Amazon is lazy loading the order page which could be causing problems based on what I see inside the innerHTML tag.  I'm surprised everyone isn't having problems.

**Comment by merak69** [comment]
![image](https://user-images.githubusercontent.com/11600344/95501943-aee18580-096e-11eb-933e-9b963ea207e6.png)

![image](https://user-images.githubusercontent.com/11600344/95501971-bc970b00-096e-11eb-86d9-cb093ed274b7.png)

**Comment by philipmulcahy** [comment]
Stuff like that happens on various payment details, which is why I’ve not yet managed to get consistent results in the payment col. If the query you're debugging is for an order detail page, then it's not the cause of seeing nothing in a table - the initial table render happens as soon as we know all the order ids, which happens once it's been through the order list page, 10 orders at a time.
The high level sequence is:
1) Get the first page of the order list - and from this get the number of orders in that year
2) Page through the order list - 10 orders at a time. For each order id create a Promise<IOrder>
3) Display the table
4) rendering of each cell waits on the subsidiary promises obtained from the order promise (because to get all the data for an order, you might need three? queries to complete)

**Comment by merak69** [comment]
The primary page for me says it expects 164 orders but when the xpath executes to find the child order elements, no results ever return.  I'm looking in "getOrdersForYearAndQueryTemplate"  which is what calls into the "findMultipleNodeValues".  The results to all of that is empty.

**Comment by merak69** [comment]
Well, I fixed it but it might be temporary if Amazon decides to remove the option.

I added a 'disableCsd=no-js' to the request listed in the "templates_by_site" struct which tells the server to render the DOM response without the CSD encryption via Javascript.  The full page is then present and the extension is able to parse everything.  This same trick might work on other pages like you were commenting regarding payment details.

**Comment by Drivium** [comment]
I'm experiencing the same issues as above. I tried checking the boxes, clearing cache, but all attempts still producing a blank table.

**Comment by Drivium** [comment]
> Well, I fixed it but it might be temporary if Amazon decides to remove the option.
> 
> I added a 'disableCsd=no-js' to the request listed in the "templates_by_site" struct which tells the server to render the DOM response without the CSD encryption via Javascript. The full page is then present and the extension is able to parse everything. This same trick might work on other pages like you were commenting regarding payment details.

Are you able to output your fixed version?

**Comment by merak69** [comment]
@philipmulcahy - Drivium didn't add it, I did.

`function fetchYear(year, scheduler, nocache_top_level) {
    const templates_by_site = {
        'www.amazon.com': [
            'https://%(site)s/gp/css/order-history' +
                '?opt=ab' +
                '&ie=UTF8' +
                '&digitalOrders=1' +
                '&unifiedOrders=0' +
                '&orderFilter=year-%(year)s' +
                '&startIndex=%(startOrderPos)s' +
                '&disableCsd=no-js' +
                '&language=en_US',
            'https://%(site)s/gp/css/order-history' +
                '?opt=ab' +
                '&ie=UTF8' +
                '&digitalOrders=1' +
                '&unifiedOrders=1' +
                '&orderFilter=year-%(year)s' +
                '&startIndex=%(startOrderPos)s' +
                '&disableCsd=no-js' +
                '&language=en_US'
        ],
`

**Comment by merak69** [comment]
I added that so it would disable the javascript dependency for the 'encryption'

**Comment by philipmulcahy** [comment]
sorry @merak69! It's strange I am unable to repro (I have a one order account in the us). I will do some more testing.

**Comment by merak69** [comment]
What logging can I add to help?  I can try to dump the order list page DOM as the extension sees it on my side if that would help.

**Comment by philipmulcahy** [comment]
Hi @merak69 
I got a csd response from Amazon on one attempt from my dev build about an hour ago, but I can't get it to do it again  (I am kicking myself for not capturing the html to paste here) Adding your url param "fixed" it, but removing it again doesn't break it either (I zapped the cache in between test runs btw).
How did you find the parameter? As far as I can see, "disableCsd" doesn't get any hits on google. I assume you are aware that you can add pretty much any parameter to the url and Amazon ignores the parameter if it doesn't recognize it (instead of rejecting the query).
If Amazon are slowly rolling out some obfuscation or security thing, us getting to the bottom of it quickly will be super valuable to azad users.

**Comment by merak69** [comment]
@philipmulcahy, I disabled Javascript to see what the page would do and Amazon itself redirected to the order page with that parameter.  After that, I added it to the code.

**Comment by philipmulcahy** [comment]
Ah! - thank you! I will add it to the next drop (crediting you of course). I intend to add it (and all of the other shared params) in a function that is applied to all of the url templates, rather than the ugly copy and paste strategy I have used so far.

**Comment by philipmulcahy** [comment]
I've pushed 1.9.15 but it Chrome Webstore being how it is these days, it might take a day or so to actually make it out to you.
Please let me know how you get on - Thank again for keeping going on this one!

**Comment by philipmulcahy** [comment]
I have the below code in the pipeline, but have another couple of small improvements to make before I push to the store (what will probably be called 1.9.16

1) download and unzip https://www.mulcahyfamily.org/azad/azad.6ccf3cd5.zip
2) open chrome://extensions
3) enable developer mode
4) disable the web store version of the extension
5) "load unpacked extension" and point to the unzipped folder
6) try it out
7) send me your log and let me know how you get on
8) remember to disable the experimental version and re-enable the web store one
