### ISSUE TITLE
Amazon.com : Only shows digital orders?

### ISSUE THREAD

**Issue by popepay** [philipmulcahy/azad#14]
Hello,

on my amazon account, the extension only pulls data from the "Digital Orders" (ebooks/...). 
All the other orders do not show.

Anyone having the same issue?

![screen shot 2018-01-04 at 2 41 23 pm](https://user-images.githubusercontent.com/17018621/34587498-6991291c-f15d-11e7-9d0d-cf1fed8117ba.png)

**Comment by philipmulcahy** [comment]
This is likely to be because your login session has (partially) expired. Try to browse manually to a non-digital order... if you get a login  prompt, log in and then retry. For some reason digital session timeouts are longer. I have a ticket to make the extension complain/warn with a help message of some sort.
Let me know how you get on.
Philip

On 4 January 2018 22:42:02 GMT, popepay <notifications@github.com> wrote:
>Hello,
>
>on my amazon account, the extension only pulls data from the "Digital
>Orders" (ebooks/...). 
>All the other orders do not show.
>
>Anyone having the same issue?
>
>![screen shot 2018-01-04 at 2 41 23
>pm](https://user-images.githubusercontent.com/17018621/34587498-6991291c-f15d-11e7-9d0d-cf1fed8117ba.png)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/philipmulcahy/azad/issues/14

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by philipmulcahy** [comment]
@popepay If this keeps happening, would you mind taking a look at what you get from:
[https://www.amazon.co.uk/gp/css/order-history?opt=ab&digitalOrders=1&unifiedOrders=1&returnTo=&orderFilter=year-2017&startIndex=0] ?
I have a suspicion that it might either give you a login prompt or show a restricted subset (digital only) or your orders.

**Comment by philipmulcahy** [comment]
No response (plus we've recently fixed a .com digital orders issue)
