### ISSUE TITLE
Can this Amazon order scrapper be implemented all on server side

### ISSUE THREAD

**Issue by ketaanhshah** [philipmulcahy/azad#149]
Hi All,
This is great extension created and works good for single user (as expected) but I wanted to know if this can be implemented on Server side if I want to bulk process multiple Amazon accounts and get their order history? Basically the all the users would give a consent and provide their user id/pwd and once we have it, is it possible to run bulk process just to extract the order history for each user all done on server side without any user intervention?

Any help/comment on the approach is apprecaited.

Thank you!

**Comment by philipmulcahy** [comment]
It is definitely possible.

The challenges are:
1) obtaining the amazon session cookies while preventing Amazon from knowing you are doing this as a server rather than an interactive user
2) getting the user to trust you
3) protecting the secrets the user would have entrusted to you
4) porting my (frankly) horrible code. 

Watch out for the terms of whatever open source license I’ve pasted onto it: you might have to share your source - I cannot remember which one I chose.

I am not trying to make money out of azad, and so these problems are effectively insurmountable in the little time I have available to work on it.

If you are minded to try, please consider:
i) you are painting a big target on yourself for anyone who might want to steal amazon accounts. This is why I would not proceed if I were you. I am reasonably knowledgeable about internet security: knowing enough to be sure that I wouldn’t stand a chance.
ii) Amazon will probably come after you. They have a legitimate justification (protecting users) and an unreasonable motivation as well: making it hard for users to access their own data.
iii) Scrapers are a real pain to maintain. It’s true that once you have users' credentials, debugging gets a lot easier, but it’s still a very frustrating maintenance challenge.

Were I to have more time, I would go around the sharing credentials issue by producing a stand alone client that users could download. (e.g. I wouldn’t ever have their creds or know anything about them) This might help with avoiding getting DoS blocked by Amazon (another problem in your future if you proceed).

Yours,

Philip

**Comment by ketaanhshah** [comment]
Thank you @philipmulcahy this is very helpful and I am going to consider all the above factors you mentioned before proceeding. I completely agree with the legal issues involved and also with the risk and maintenance involved with the credentials. Appreciate your help and detailed response.
