### ISSUE TITLE
Order/item category extraction

### ISSUE THREAD

**Issue by iloveitaly** [philipmulcahy/azad#169]
I'd love to be able to see which category an item was in, or most of the order was in.

Could you point me to the best place in the code to add this? I may be able to hack this in and submit a PR.

**Comment by iloveitaly** [comment]
@philipmulcahy thank you for the reply!

My thought is to display the whole category breadcrumb path. That's great to know about the secret pack of test data. Thanks!

Could you help me with one more detail: how do you run the scraper against a single order page to test new logic? What's the best development loop for testing extraction of new data from an amz page?

Thanks!

**Comment by iloveitaly** [comment]
@philipmulcahy I was able to get a debugging setup with a single order, so I'm good there.

It seems like the only way to extract the category is to pull the product page and extract the category breadcrumb from there. It seems like the easiest way to do this is to make another request to grab the product page and then extract the data from there.

https://github.com/philipmulcahy/azad/blob/master/src/js/item.ts#L77

Two questions for you:

1. What's the best way to access the scheduler from that point in the code?
2. Any reason why I can't use `await` in the `strategy*` methods instead of a promise callback?

**Comment by philipmulcahy** [comment]
Hi @iloveitaly,

1) We could pass the scheduler from order.ts, which would mean adding a param to ItemsExtractor and then params to the various implementing strategies. Can you think of another strategy? One possible concern here is performance: more fetches == slower and more likely to trigger anti-crawling protection by Amazon, so that users who are currently getting away with their scrapes start getting blocked. For this reason, I think we should put the additional behaviour behind a feature flag controlled by the UI (another checkbox). The converted fetches should be cached in the azad cache.

2) I don't think so. Some history" I stopped being a full time coder (sigh) around the time MS dropped the await demo in C# - a good few years ago. This means I have never properly used await in any language except maybe a bit in python. This extension was originally written in schoolboy js (it was the project I used to learn the language), and was then transmuted to ts because the code base grew enough that not having static types was becoming a bit of a drag. While I was doing this, various async features were added to the language and I got a tiny bit more experienced, but I never invested in a clean-up refactor. I think that promises are probably required for some of the code (where it assembles arrays of promises and waits for them all before continuing), but if you think await works more cleanly for what you're trying to do, I'd be keen to see your approach.

Yours,

Philip

**Comment by iloveitaly** [comment]
@philipmulcahy I implemented the category scraping in this PR https://github.com/philipmulcahy/azad/pull/175. Agree with you on a UI option, but I don't have the time. Hopefully someone can take what I did and improve it.

**Comment by philipmulcahy** [comment]
d6cf6ac (heavily updated version of one of @iloveitaly's PRs, with tests and UI setting checkbox wired in) fixes this, and I just merged it into master - expect to see it in the next couple of weeks.

**Comment by philipmulcahy** [comment]
v.1.11.0 in review with the webstore: expect it to deploy in the next week
