### ISSUE TITLE
Total amount of all orders.

### ISSUE THREAD

**Issue by Remonell** [philipmulcahy/azad#170]
Hi,

I would like to know what I spent in total on amazon. Would be great if you could implement such a feature.

**Comment by philipmulcahy** [comment]
it can do it for each year already: I assume you’d be willing to add together a the year totals yourself?

**Comment by philipmulcahy** [comment]
Here's my 2021 running total:
![image](https://user-images.githubusercontent.com/1668892/140593642-3c654ef9-b297-4672-917d-484995c07878.png)
It works similarly for all the other available years.
I assume you can get something similar.
If I don't hear differently, I'll close this ticket next time I pass through this project.

**Comment by Remonell** [comment]
Yes, I guess I could do it for the last 15 years each and then manually add it all together. But a specific function for all the years available would be great. Do you accept PRs if I create one for that feature?

**Comment by philipmulcahy** [comment]
I do accept PRs, though as you might expect sometimes with some back and forth in review.
One roadhump that might bite us is the definition of “All”.
At the moment the extension won’t look further back than 2004, because Amazon’s coverage of many orders is broken beyond that.
I regularly get complaints about this, but the alternative is more complaints about corrupted data.
