### ISSUE TITLE
Trigger history export by script

### ISSUE THREAD

**Issue by wi6436** [philipmulcahy/azad#183]
The extension is really a huge help, thanks for this great software!

I'm trying to find a way to run the history export regularly by means of a script and/or cron job. My naive approach would be trying it somehow with selenium, but maybe somebody did this already or there is a much simpler way. Therefore I would like to ask here first,

is there any such method to trigger the history export programmatically through scripting?

Thanks a lot for any help or ideas!

**Comment by philipmulcahy** [comment]
My initial thoughts are that:
1) It could be accomplished more cleanly than by pretending to be a user clicking buttons - you should probably take a look at the way the different parts of the extension communicate with each other. Off the top of my head, I think there are at least three bits: i) the control popup page; ii) the background/server page (which I think changed from being somewhat persistent to being on-demand; iii) the injected content script in the amazon web page. These bits exchange messages with each other to collaborate, because it turns out that none of them can deliver all of the functionality needed on their own.
2) Your use case (unknown to me) might be problematic from the perspective of Amazon's undeclared behaviour towards scraping. Users with lots of orders in a year they are scraping sometimes get logged out by one or more of the backend services Amazon must be using to support their web UI. That's the main reason I added the query cache, to enable them to make forward progress at all, not to expedite something that already worked.
3) You probably want to think about authentication. The extension as it stands does not get involved in authentication other than to detect when you seem not to be properly logged in. I like it this way, because it reduces the chance that my code is ever used as part of a credential stealing attack.
4) None of the routes I can imagine right now would be acceptable to me for the public version because of the security risks (and likelihood of getting blocked by the web store). I don't rule out the possibility of a nice way to do it, but for me to merge a pull request would require me to be reasonably convinced it was safe - if you want quick and dirty, you are always free to use UI testing tools (such as you allude to), or maintain a fork.
Yours,
Philip

**Comment by ScottMcNay** [comment]
To wi6436,

I'm thinking the simple way would be to use a script to log off of Amazon
(so you have a known starting point), log on (it's your script, so you can
feel free to give it your login id and password), then run the extension.

--Scott.

**Comment by wi6436** [comment]
Hi @philipmulcahy, @ScottMcNay,

thanks a lot for your quick and detailed answers!

1) Thanks for this overview description of your code. It sounds that the button interface is actually quite well separated from the backend code, which seems to be ideal for basing a scripted solution on it. I will definitively have a look and try to understand your code better - I believe this is very valuable.
 
2) My use case is bookkeeping of orders and withdrawals without too many manual steps. If it is done once per day, it should be enough. Hopefully this is below the anti-scraping threshold.

3), 4) @ScottMcNay Yes, I have already realized that authentication is not supported and I fully understand the concerns behind having this available in a public version. Maybe, this is not also necessary even for an automatic solution, as I think I have never seen an inactivity logout on Amazon's pages. Otherwise I'll try somehting as ScottMcNay describes it.

Many thanks again!

**Comment by philipmulcahy** [comment]
I've built (and pushed) an inter-extension API for a commercial outfit that proposed to fund the charity I do this for. They have since gone silent, so I'll eventually tidy it up, but you might find it interesting: here's the merge commit: 1fcb436af1bbe80d597fbb0e9608977741a085ce
