### ISSUE TITLE
Fragen zu Amazon Order History Reporter

### ISSUE THREAD

**Issue by joerg1111** [philipmulcahy/azad#195]
Guten Tag.

Warum steht in der Spalte **"Zahlungen"** bei **Lieferungen unbekannt? Zahlbetrag und Zahldatum** steht nur bei **Downloads**.
(Seh ich das richtig, dass englische Wörter automatisch in Deutsch übersetzt werden und wenn man das nicht will, dass man dann das Wort in Anführungszeichen (") setzen muss? Allerdings wird das Wort "Zahlungen" übersetzt in **Rechnung** aber **Zahlung bleibt Zahlung**.  Ob übersetzt wird hängt auch davon ab wo das Wort steht.

Eine Leerzeile rein und schon ist wieder anders.

Ist das ein Fehler?

 Das Wort "Zahlungen" ohne Anführungszeichen wird sogar weggelassen im Text aber nur in dieser Zeile??? Warum wird der Text nicht 1:1 übernommen? "Wird" wird grossgeschrieben obwohl ich es kleingeschrieben habe.

Manchmal verändert sich auch der Satzbau und ganze Texte werden weggelassen)

![image](https://user-images.githubusercontent.com/88881052/177532059-bdafb695-48e7-4968-ae83-6f08d3f3ba64.png)

----------------------------------------

Ich hatte gelesen, dass man auch die **Zahlungsart** sehen kann aber das ist nicht so. Das steht hier:

https://www.pcwelt.de/ratgeber/So-viel-Geld-haben-Sie-bisher-bei-Amazon-ausgegeben-Trick-verraet-alles-11022741.html

![image](https://user-images.githubusercontent.com/88881052/177532539-5192a84d-7373-4ace-8847-feb5547cad47.png)

---------------------------------------

Warum rechnet die Erweiterung nicht die **Gesamtsumme aller Bestellungen aller Jahre zusammen** so dass man die Jahre nicht einzeln addieren muss?

-----------------------------------------

Wofür ist  "show items not orders" ?     (Warum wird das übersetzt? Ich hab das in englisch geschrieben wie im Screenshot. Hier nützen die Anführungszeichen auch nichts)

![image](https://user-images.githubusercontent.com/88881052/177532792-9aaa7308-49bd-41c5-a779-a12e8b002f2a.png)

**Comment by joerg1111** [comment]
Sorry, again in english:

Why does the column Payments for **deliveries** say **unknown**? **Payment amount and payment date** is only for **downloads.**
![image](https://user-images.githubusercontent.com/88881052/178053198-2122dc60-123d-449a-a113-6a6df2cc302d.png)

***

I had read that you can also see the **payment method** but that is not so. That is what it says here:

https://www.pcwelt.de/ratgeber/So-viel-Geld-haben-Sie-bisher-bei-Amazon-ausgegeben-Trick-verraet-alles-11022741.html

Quote:
![image](https://user-images.githubusercontent.com/88881052/178053337-f9e102b1-4c23-4130-bfd1-6807986a6993.png)

***

Why doesn't the extension **add up the total of all orders of all years** so that you don't have to add up the years individually?

***

What is Display **show items not orders?**

![image](https://user-images.githubusercontent.com/88881052/178053547-95aaf983-d1fe-4751-9826-93953abca268.png)

**Comment by ScottMcNay** [comment]
> Why doesn't the extension add up the total of all orders of all years so
that you don't have to add up the years individually?

Handling more than a year at a time has always been problematical,
especially for people who have a LOT of orders.


> What is Display show items not orders?

Each order can contain more than one item.

--Scott.

**Comment by joerg1111** [comment]
> What is Display show items not orders?
 Each order can contain more than one item.

Did I understand this correctly?:

When **activating** this option, for **different items** each item of the same order is listed in an extra line with the respective price. For multiple quantities of **the same item**, there is the Quantity field but only single price and no total price. Why is there no total price?
Why is there no total of all items as when this option is disabled?


When **disabling** this option, for **different items** all items of the same order are also listed but without unit price but only with total price.
For multiple quantities of **the same item**, the quantity and unit price is not apparent.


I think the term **show items not orders** is therefore confusing. Suggestion: **show unit price per item and quantity**.


What about my other questions? Why does it say **unknown** for **payments**?
Only for downloads it is displayed correctly. But not for deliveries.

And why is the payment type not displayed as described in the PC-Welt article?


Additionally I noticed:

Why is the Amazon page always switched to English? You always have to manually change the page to German.

Sometimes you get logged out and you have to log in again. 

Thank you very much for your effort.

*****

In Deutsch:


Hab ich das so richtig verstanden?:

Bei  **Aktivierung** dieser Option wird bei **unterschiedlichen Artikeln** jeder Artikel derselben Bestellung in einer Extrazeile mit dem jeweiligen Preis gelistet. Bei mehreren Stückzahlen **desselben Artikels** gibt es das Feld Menge aber nur Einzelpreis und keinen Gesamtpreis. Warum gibt es keinen Gesamtpreis?
Warum wird keine Gesamtsumme aller Artikel angegeben wie bei Deaktivierung dieser Option?


Bei **Deaktivierung** dieser Option werden bei **unterschiedlichen Artikeln** zwar auch alle Artikel derselben Bestellung gelistet aber ohne Einzelpreis sondern nur mit dem Gesamtpreis.
Bei mehreren Stückzahlen **desselben Artikels** ist die Stückzahl und der Einzelpreis nicht ersichtlich.


Ich denke, die Bezeichnung **show items not orders** ist deshalb verwirrend. Vorschlag: **Einzelpreis pro Artikel und Menge anzeigen**.


Was ist mit meinen anderen Fragen? Warum steht bei **Zahlungen unbekannt**?
Nur bei Downloads wird es korrekt angezeigt. Aber nicht bei Lieferungen.

Und warum wird die Zahlungsart nicht angezeigt wie in dem Artikel der PC-Welt beschrieben?


Zusätzlich fiel mir auf:

Warum wird die Amazon Seite immer auf englisch umgestellt? Man muss die Seite immer manuell auf Deutsch umstellen.

Manchmal wird man ausgeloggt und man muss sich neu anmelden. 

Vielen Dank für Ihre Mühe.

**Comment by ScottMcNay** [comment]
Hi,

There are several issues which cause problems.

The first issue is that digital items and physical items are handled
differently. So, when Amazon makes a change, one can break but not the
other.

Each region and language is also handled differently (data is requested in
English, to help improve consistency), so something can break for a
region/language as well.

The logout is another issue that requires workarounds and causes problems.

Please follow the steps on the Troubleshooting page and send the requested
sample data to the email address given on the page, and Philip will take a
look at it when he has time.

--Scott.

**Comment by joerg1111** [comment]
Thank you for your answer but I still have questions:

> What does "show items, not orders" mean?
> Each order can contain more than one item.

And did I understand it correctly as I described above?

Again my question:
And why is the **payment type** not displayed as described in the PC-Welt article?


Quote:

> Generic work-arounds
> Your first step should be to go to chrome://extensions and click Update. After you do this, close and reopen the Amazon page and rerun the report to see if that helped.
> 

On your page it says to click on **update** but there is no update button there:

Do you absolutely need the Amazon address?
Do you need the log file and debug json file?






> Please follow the steps on the Troubleshooting page and 
send the requested
sample data to the email address given on the page, 

Should this be sent to the following mail?
azadextension@gmail.com

You surely mean the following website at the Overview tab because of bug fixes
https://chrome.google.com/webstore/detail/amazon-order-history-repo/mgkilgclilajckgnedgjgnfdokkgnibi

Your page says:
> Currently supported:
> amazon.com.au, .ca, .de, .es, .in, co.uk, com, .com.mx (partial).
> 
> For other Amazon sites, please submit debug information as described in https://github.com/philipmulcahy/azad/blob/master/README.md

My language is German. Do you still need the debug information?

**********

in Deutsch:


Vielen Dank für Ihre Antwort aber ich habe noch Fragen:

> Was bedeutet "Artikel anzeigen, nicht Aufträge"?
> Jeder Auftrag kann mehr als einen Artikel enthalten.

Und habe ich das so richtig verstanden wie ich es oben beschrieben habe?


Nochmal meine Frage:
Und warum wird die **Zahlungsart** nicht angezeigt wie in dem Artikel der PC-Welt beschrieben?


Zitat:

> Generic work-arounds
> Your first step should be to go to chrome://extensions and click Update. After you do this, close and reopen the Amazon page and rerun the report to see if that helped.

Auf Ihrer Seite steht, dass man auf **Update** klicken soll aber dort gibt es keinen Update Button:

Benötigen Sie unbedingt die Amazon Adresse?
Benötigen Sie das Log file und debug json file?
`


> Please follow the steps on the Troubleshooting page and 
send the requested
sample data to the email address given on the page, 

Soll das an folgende Mail geschickt werden?
azadextension@gmail.com

Sie meinen sicherlich folgende Website beim Reiter Übersicht wegen Fehlerbehebungen
https://chrome.google.com/webstore/detail/amazon-order-history-repo/mgkilgclilajckgnedgjgnfdokkgnibi

Auf Ihrer Seite steht:
> Currently supported:
> amazon.com.au, .ca, .de, .es, .in, co.uk, com, .com.mx (partial).
> 
> For other Amazon sites, please submit debug information as described in https://github.com/philipmulcahy/azad/blob/master/README.md

Meine Sprache ist deutsch. Benötigen Sie denn trotzdem die debug Information?

**Comment by philipmulcahy** [comment]
Hi Joerg,

There are a few problems with how you've reported this problem (or should I say these problems), but the most critical (at least from my perspective) is that you are being a little disrespectful. I was tempted to just ignore the ticket and wait for you to get bored and go and complain about something else, but then you were somewhat rude to Scott. I imagine he doesn't see it like that (as he is a nice guy, unlike me), but I thought I'd give you some feedback...

1) RTFM - you've not properly read the (basic) instructions - I can tell this because you posted in German. For me (having workable german), this is more of a "no brown M&Ms" thing (look it up) than a real obstacle.
2) Consider that no-one working on this project gets paid for it. What makes your request the one they choose to work on?
3) Split the problems you have discovered into separate tickets - how can we possibly manage them all merged into one rant? Please don't do this until you've internalised the rest of this post.
4) Be constructive: consider how can you help?
5) What has an article in pcwelt got to do with me (or Scott)? I didn't write it, or contribute to it in any way. Have you written to them to complain as well? (I'd love to see how you got on!)
6) Recognize that scraping projects are extremely vulnerable to the "moving target" problem. Amazon can break the extension any time they feel like it, and sometimes they do so without even trying. I don't have an amazon.de account and more specifically I don't have access to your account, so how do you suggest I go about investigating your unexpected output? I have rough and ready methods, but they rely on persistent helpfulness from bug reporters. It turns out that most self entitled complainers rarely have the stamina to work through the process. Per the readme, it's not worth sending me anything on the extension's gmail account until we've agreed what it is we're investigating - I won't read it. (I ignore several thousand emails per week at my real job - ignoring yours won't be too challenging).

Yours,

Philip

**Comment by joerg1111** [comment]
Good day, Philip.

I apologize very much for posting in German. But I had apologized for it and all further posts are in English or English and additionally German.




I didn't know that I have to take a seperate ticket for each question, sorry.

I just wanted to know for interest why pc Welt writes that the payment method is shown and if this information is possibly wrong from pc Welt. This was in no way meant as a complaint.

I wanted to know some things and understand it exactly and that's why I asked.
I repeated some questions because apparently some questions were accidentally read over. Is that rude?

I did not mean to be rude or disrespectful at all and that was absolutely not my intention. I don't know at what point I was rude.

Also, I was just asking questions and in no way was this meant to be a complaint.

Maybe some things come across wrong because I translate with Deep L.

I hope that you will accept my apology.

Have a nice day.


***

Auf deutsch.

Guten Tag, Philip.

Entschuldigen Sie vielmals, dass ich auf Deutsch gepostet habe. Aber ich hatte mich dafür entschuldigt und alle weiteren Posts sind auf englisch bzw. englisch und zusätzlich deutsch.

Ich wusste nicht, dass ich für jede Frage ein seperates Ticket nehmen muss, sorry.

Ich wollte einfach nur interessehalber wissen, warum die pc Welt schreibt, dass die Zahlungsart angezeigt wird und ob diese Information möglicherweise falsch ist von der pc Welt. Das war in keinster Weise als Beschwerde gedacht.

Ich wollte einige Dinge wissen und es genau verstehen und deshalb fragte ich nach.
Ich wiederholte einige Fragen weil anscheinend versehentlich einige Fragen überlesen worden. Ist das unhöflich?

Ich wollte keinesfalls unhöflich und respektlos sein und das war absolut nicht meine Absicht. Ich weiss nicht an welcher Stelle ich unhöflich war.

Auch stellte ich nur Fragen und keinesfalls sollte das eine Beschwerde sein.

Womöglich kommt einiges falsch rüber weil ich mit Deep L. übersetze.

Ich hoffe, dass Sie meine Entschuldigung anerkennen.

Ich wünsche noch einen schönen Tag.

**Comment by philipmulcahy** [comment]
Hi Joerg,

Apology accepted - sorry for being so grumpy.

Payments...
Sometimes the extension is able to get payment info, and sometimes it isn’t. Because I use amazon.co.uk and therefore have access to experiment freely it’s probably a bit better at that variant than the others, but it’s far from perfect even there.
The obstacles are somewhat tough to overcome - when you see (for example) a picture of a credit card of the right kind, and maybe the last four digits of the card number, you may not realise that it’s often been rendered dynamically in the page by a complicated javascript call that in turn makes a call to a one-time URL that itself is generated by the javascript.
To get the card data, we’d have to either completely replicate all of the javascript loading and running for every order page the extension fetches (very very slow when you’re fetching hundreds or thousands of orders), while managing to fool the scripts into thinking they were being run in a normal page-load scenario (which is potentially dubious/adversarial), or we’d need to have the extension code find the bit of the amazon script that generates the URL and run it to get the URL, but stop it from using it, because it’s a one-time thing, and we want our code to run it.

A couple of years ago I spent quite a few evenings trying to figure out how to make it work, but couldn’t. If you look at Amazon’s javascript you’ll find that the most interesting parts of it have been minified and in some cases properly obfuscated: they don’t want folks picking apart their sensitive customer data flows. I am very interested to hear if you have ideas of a potentially viable strategy to improve payment fetching.

If you are so inclined, I recommend you take a look at chrome’s network debugging tool, which logs every web call made by a page load. I chose a random order of mine and estimate loading it caused 100 url fetches.

features.

Yours,

Philip

**Comment by philipmulcahy** [comment]
Assuming this is OK now - closing
