### ISSUE TITLE
Amazon UK Large History Issue

### ISSUE THREAD

**Issue by shahmohsinalam** [philipmulcahy/azad#22]
[www.amazon.co.uk-1528081520481.log](https://github.com/philipmulcahy/azad/files/2066739/www.amazon.co.uk-1528081520481.log)

Hi i have about 10,000 orders in 2018. When i click on the 2018 orange button it starts loading the orders up and runs 6 orders typically. After a few minutes this number drops to zero and i have to login to amazon on a different tab and reclick on 2018 to continue. Having done this for past couple of hours, iam now showing the following: queued:130637; running:6; completed:6609; errors:155

I have not seen the excel spreadsheet yet, does this process usually take this long for this many orders? thanks

**Comment by philipmulcahy** [comment]
Interesting...

10k is more orders than I have so haven't managed to test that high. A complete run should end up with slightly more than two queries per order - your numbers suggest you have a higher pain threshold than I have :)
6 is the maximum number of queries Chrome will let you run simultaneously against one website.
The counters keep counting up for a new run if you don't refresh the window and I now realise that's confusing. I think I should cause them to reset when you hit an orange button.

In order to help me debug this, would you mind capturing the console log from chrome's developer tools:
1) Chrome developer console (three dot icon/button on right hand side|More tools|Developer Tools)
2) Click on Console (in a bar near the bottom normally)
3) Press the orange year button you want to fetch
4) Respond at least once to the re-login prompt if it happens.
5) Watch the console fill up with logs, and wait for stuff to stop happening in the counters on the top right hand side.
6) Right click somewhere in the console logs | Save as... (choose a file name)
7) Drag the file to a comment box in this ticket.
[although order ids end up in the log (and offer useful clues about digital/non-digital), I and others cannot use them to look at your orders or other account info.]
After looking at that file, It's possible I might then need to push a version with more diagnostic logging and for you then to repeat the log capture exercise.

Yours,

Philip

**Comment by philipmulcahy** [comment]
Hi @shahmohsinalam,
I've just noticed you've already included a log, (sorry for regurgitating the instructions on you).
It's too short... e.g. we don't see any of the same orders being re-requested. Is it possible you didn't save all of it?
Philip

**Comment by philipmulcahy** [comment]
@shahmohsinalam 
I'm working on a performance improvement that caches results from queries to Amazon, so retries are much faster - it needs some more testing before I push it though... I'll let you know.

**Comment by philipmulcahy** [comment]
closing - please re-open if you disagree!
