### ISSUE TITLE
Process runs but report isn't created

### ISSUE THREAD

**Issue by elusis** [philipmulcahy/azad#222]
Browser is Chrome for Mac  114.0.5735.198
Mac OS Ventura 13.4
Extension is up to date

I have: 
Cleared the cache before starting fetch (which I always do)
Logged out of Amazon and in again
Deleted all Amazon cookies
Restarted browser

And I am still getting the same results as below.

<img width="323" alt="Screenshot 2023-07-02 at 4 45 48 PM" src="https://github.com/philipmulcahy/azad/assets/30632059/e14b44bc-b986-44a1-8d5e-52eba5e5eb67">

**Comment by yumbrad** [comment]
This also happens to me, though in my case there are a few errors (perhaps due to Amazon Fresh orders? There are 13 orders that give a 500 response when trying to access their order detail page). I wish I could download the CSV of all the successful orders, but because of the 13 errors, the download link is not created.

**Comment by philipmulcahy** [comment]
thanks for reporting this!
I think there a bunch of similar bugs that I thought I'd solved in a recent update, but clearly not fully.
I'm working on shipment data right now, but the next project will be building a test rig that simulates 500s and other errors to see how azad copes with them.

**Comment by philipmulcahy** [comment]
I did a cheapo version of the test rig today _after_ a bunch of concurrency changes, and found a bug that _might_ have explained what you saw. Expect a new version in the next week or two.
