### ISSUE TITLE
Orders past Jun 15th not showing

### ISSUE THREAD

**Issue by RiZaJJ** [philipmulcahy/azad#229]
Tried clear cache, different browser (Brave and Chrome), but both show all orders up until June 15 2023 and nothing after. I see some other reports of not loading all orders but I'm not sure this is the same issue? Sorry if this is a dupe.

**Comment by philipmulcahy** [comment]
This doesn't give me much to go on, as I don't have access to your account - you could start by attaching your console log (see the README doc).
In the meantime, it might be worth considering if you've got an order type that the extension doesn't know how to handle - you might benefit from looking at the log yourself to see if anything jumps out as suspicious.

Though I've never done it myself, on various reported issue threads folks have described "archiving" orders that apparently break the extension, allowing subsequent scrapes to continue and succeed - they seem happy with the result - typically (b but not always) ceasing to provide me with more debug info.

I would like to improve Azad such that:
1) bogey orders (e.g. ones that my code is unable to process, either due to a bug or lack of feature work) are clearly reported as such in the logs
2) the overall scrape continues unimpeded, and does not fail disproportionately.

Right now I am very squeezed for time at my day job, and need to spend nearly all of my azad time on two things:
i) moving the currently paywalled features to free access once their 5k charity target is reached (real soon now)
ii) refactoring the code so that shipments/deliveries are extracted - once (i) lands, potential new subscribers will be getting nothing for their donations, and I know that lots of 'em shipment data.
that means that for the time being I'm not going to work on bugs that are not both:
a) impacting multiple users
b) reported with enough detail to make attacking them feasible.

Yours,

Philip

**Comment by philipmulcahy** [comment]
no response for 2 months
