### ISSUE TITLE
Amazon Grocery Tips

### ISSUE THREAD

**Issue by axjasf** [philipmulcahy/azad#238]
In the US, for Amazon Grocery orders, there's a tip option. This is somewhat reflected in the payment string on the header level, but there's no column (such as "total", "return" etc.) that states the tip on the header level. The tip is part of the individual order page and can be seen on the screen.

**Comment by philipmulcahy** [comment]
Table stakes for this one is at least three debug json files for orders displaying this behaviour so that whoever picks it up has a chance at being able to pick through the html, code the feature and add a regression test. You should email them to the project's email address (with this issue's title and number in the subject), and post back here to say you've done it.

**Comment by philipmulcahy** [comment]
closing in about a month if no-one's given me the ammunition I need to address this wish.

**Comment by philipmulcahy** [comment]
user went dark -> closing
