### ISSUE TITLE
Coupon savings

### ISSUE THREAD

**Issue by axjasf** [philipmulcahy/azad#239]
In the US, there's the ability to collect coupons and redeem them. The order page has a field "Your coupon savings" which is on the same level than "total" or "refunds", but it does not show up on the header list. All the items (quantity * price) do then not add up with common costs to the final payment amount.

**Comment by philipmulcahy** [comment]
Table stakes for this one is at least three debug json files for orders displaying this behaviour so that whoever picks it up has a chance at being able to pick through the html, code the feature and add a regression test. You should email them to the project's email address (with this issue's title and number in the subject), and post back here to say you've done it.

**Comment by philipmulcahy** [comment]
closing in about a month if no-one's given me the ammunition I need to address this wish.

**Comment by philipmulcahy** [comment]
user went dark -> closed
