### ISSUE TITLE
Order Total .de not working - is not added together

### ISSUE THREAD

**Issue by Chriss122** [philipmulcahy/azad#261]
Hi,

previously we had already fixed the bug with the , and . for US and DE -> now unfortunately the total is not added up.
I suspect exactly the same error here with . and , as there is a . in the total and the totals of the orders are all evaluated with ,

Maybe you can have a look at it.
![total](https://github.com/philipmulcahy/azad/assets/22147563/29aef638-067c-45ff-ba18-7a6d0b007fb9)

Greetings
Chriss

**Comment by philipmulcahy** [comment]
I am out of the country on business this week - will look when I get back!

**Comment by philipmulcahy** [comment]
Would you mind sending me a couple of [order json debug files](https://github.com/philipmulcahy/azad?tab=readme-ov-file#how-to-save-and-send-an-order-debug-json-file) for orders in that screenshot - perhaps the one with the shipping, and the 15.99 one?

I have a single (2018) order on amazon.fr, for which the table gets the totals correct, but the order text has"EUR X.YZ" rather than "€ X.YZ". I've added a unit test for "€ 123.45" with and without a space, and it's coping fine, so I'm wondering if there's something else hidden going on in the html you're being served.

**Comment by Chriss122** [comment]
thanks for the fast reply.

I have sent you the debug info by e-mail

**Comment by philipmulcahy** [comment]
https://www.mulcahyfamily.org/azad/azad_1a0757c5.zip might fix it - here's how to try it out: https://github.com/philipmulcahy/azad?tab=readme-ov-file#how-to-try-out-an-experimental-version

If it it works (please let me know!), I'll merge the fix into the next proper release.
If not, we can regroup and capture some more diagnostics.

Yours,

Philip

**Comment by Chriss122** [comment]
Hi Philip,

that works -> tested for a whole year and monthly reports.
thanks for the fast response and bugfix! =)

Greetings
Chris

**Comment by philipmulcahy** [comment]
I'll keep this open until I push a proper release out.
