### ISSUE TITLE
How do I unsubscribe?

### ISSUE THREAD

**Issue by philipmulcahy** [philipmulcahy/azad#264]
You've subscribed, but you've decided that this year is enough, and want to stop future billing events.

**Comment by philipmulcahy** [comment]
Here's how (four steps):

1) Open the extension's pop-up window.
2) Click on the grey "preview features" button.
<img width="407" alt="Screenshot 2024-02-12 at 22 34 24" src="https://github.com/philipmulcahy/azad/assets/1668892/24a10a3a-afde-4adc-b120-8d13ad893e1a">

3) Click on the grey "renew log-in if you've paid" button.
<img width="322" alt="Screenshot 2024-02-12 at 22 34 49" src="https://github.com/philipmulcahy/azad/assets/1668892/b9081fa0-e8b0-4fb2-a1fc-34e3bfc46154">

4) Click on the "cancel" link, next to the rate amount.
<img width="500" alt="Screenshot 2024-02-12 at 22 35 09" src="https://github.com/philipmulcahy/azad/assets/1668892/bc6bd48a-1407-43d9-a583-6eb7cd5def5c">

**Comment by philipmulcahy** [comment]
If you have a 7.50 one: don’t cancel it in haste: it will renew at the same price (unless you cancel it).I hiked the rate for new subscribers last week ‘cos some users have been naughty and dealing with them has consumed infeasible amounts of my energy: it is a bit of a “tragedy of the commons” situation.I will poke around on stripe to see if you have two (not at home right now): can you let me know your email addresses please? (Send them in a note with #264 in the subject to ***@***.*** so that no one else sees your addresses)Sent from my phoneOn 9 May 2025, at 15:28, weigelf ***@***.***> wrote:﻿
weigelf left a comment (philipmulcahy/azad#264)
Philip,
I DO NOT want a refund.
Thank you for putting this extension together. I'm using it in MS Edge, Win11, with no problems. I just started today.
Please keep/contribute the donation and the subscription money you have received from me, but please reply when you get a spare moment.
When I went to purchase (not donate) the extension, I saw the charge as US $7.50 per year. After I hit the purchase button, it showed $15.00 per year.
What is the correct price, please? I think I may have somehow purchased 2 copies of the extension.
Again, please keep everything I donated/paid thus far.
I DO NOT want a refund.
I just want to correct the price to $7.50 before next year, if that's the correct price.
Thank you again for this great extension. This is saving me a lot of time.
All the best,
Fred W.

**Comment by weigelf** [comment]
This is a test to see if the email is masked

 

***@***.*** ***@***.***>  – not a real address.

 

 

  <https://avatars.githubusercontent.com/u/1668892?s=20&v=4> philipmulcahy left a comment (philipmulcahy/azad#264) <https://github.com/philipmulcahy/azad/issues/264#issuecomment-2866953109> 

If you have a 7.50 one: don’t cancel it in haste: it will renew at the same price (unless you cancel it).I hiked the rate for new subscribers last week ‘cos some users have been naughty and dealing with them has consumed infeasible amounts of my energy: it is a bit of a “tragedy of the commons” situation.I will poke around on stripe to see if you have two (not at home right now): can you let me know your email addresses please? (Send them in a note with #264 in the subject to ***@***.*** <mailto:***@***.***>  so that no one else sees your addresses)Sent from my phoneOn 9 May 2025, at 15:28, weigelf ***@***.*** <mailto:***@***.***&gt> &gt; wrote:﻿ <br> weigelf left a comment (philipmulcahy/azad#264) <br> Philip, <br> I DO NOT want a refund. <br> Thank you for putting this extension together. I&#39;m using it in MS Edge, Win11, with no problems. I just started today. <br> Please keep/contribute the donation and the subscription money you have received from me, but please reply when you get a spare moment. <br> When I went to purchase (not donate) the extension, I saw the charge as US $7.50 per year. After I hit the purchase button, it showed $15.00 per year. <br> What is the correct price, please? I think I may have somehow purchased 2 copies of the extension. <br> Again, please keep everything I donated/paid thus far. <br> I DO NOT want a refund. <br> I just want to correct the price to $7.50 before next year, if that&#39;s the correct price. <br> Thank you again for this great extension. This is saving me a lot of time. <br> All the best, <br> Fred W. <br> <br> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.*** <mailto:***@***.***&gt> &gt;

**Comment by weigelf** [comment]
Hi Philip,

 

The purchase would have gone through as either 

 

***@***.*** ***@***.***> 

or 

***@***.*** ***@***.***> 

 

Stripe has the former, but I think I used the latter when I did the donation.

 

Have a great day,

Fred

 

 

  <https://avatars.githubusercontent.com/u/1668892?s=20&v=4> philipmulcahy left a comment (philipmulcahy/azad#264) <https://github.com/philipmulcahy/azad/issues/264#issuecomment-2866953109> 

If you have a 7.50 one: don’t cancel it in haste: it will renew at the same price (unless you cancel it).I hiked the rate for new subscribers last week ‘cos some users have been naughty and dealing with them has consumed infeasible amounts of my energy: it is a bit of a “tragedy of the commons” situation.I will poke around on stripe to see if you have two (not at home right now): can you let me know your email addresses please? (Send them in a note with #264 in the subject to ***@***.*** <mailto:***@***.***>  so that no one else sees your addresses)Sent from my phoneOn 9 May 2025, at 15:28, weigelf ***@***.*** <mailto:***@***.***&gt> &gt; wrote:﻿ <br> weigelf left a comment (philipmulcahy/azad#264) <br> Philip, <br> I DO NOT want a refund. <br> Thank you for putting this extension together. I&#39;m using it in MS Edge, Win11, with no problems. I just started today. <br> Please keep/contribute the donation and the subscription money you have received from me, but please reply when you get a spare moment. <br> When I went to purchase (not donate) the extension, I saw the charge as US $7.50 per year. After I hit the purchase button, it showed $15.00 per year. <br> What is the correct price, please? I think I may have somehow purchased 2 copies of the extension. <br> Again, please keep everything I donated/paid thus far. <br> I DO NOT want a refund. <br> I just want to correct the price to $7.50 before next year, if that&#39;s the correct price. <br> Thank you again for this great extension. This is saving me a lot of time. <br> All the best, <br> Fred W. <br> <br> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.*** <mailto:***@***.***&gt> &gt;

**Comment by philipmulcahy** [comment]
Score one for github! It's redacted your email addresses - that's not why I asked you to send 'em to azadextension at gmail dot com, but it's another good reason: facepalm on my side too - I thought that it knew that the extension's email address was public knowledge and it didn't need to zap it.

**Comment by philipmulcahy** [comment]
I've figured out @weigelf's email addresses and initiated direct contact - let's end public discussion here unless anyone else thinks that they were charged a different price to the one they were offered.

Some background:
1) At the moment, annual renewals are the same as your initial sign-up cost, which means that folks who subscribed earlier have been getting lower renewals. I believe the price trajectory was $5, then $7.50, and currently $15. There are not many $5 subscriptions still active, but there are lots of $7.50 ones still going.
2) Q: Why did you raise the price? A: A small number of users ignore the signup warnings about chargebacks. These cost the charity many multiples of the subscription price in non-refundable middleman charges, and consume insane amounts of my time to defend. So far, while the odd card issuer has sided with their customer, no evidence has been presented to suggest that I (philip) am the bad guy - I am of the opinion that all chargeback attempts so far are either customer error or dishonesty.
3) Q: and? A: This is why new subscribers can't have $7.50 pricing - it's not worth my time.
4) Q: are you doing anything else about the bad users? A: yes - I am exploring minimal usage logging of subscribed users' extension activity (not leaking any of their amazon account info), so that they cannot subsequently claim that they didn't use the extension: the credit card providers seem to see such records as table stakes for challenging a charge-back attempts.
