### ISSUE TITLE
Unable to scrape any transactions occurring during a specific time window

### ISSUE THREAD

**Issue by TrekLurker** [philipmulcahy/azad#267]
As the title indicates, and following all debug suggestions (clear cache/cookies), repeated successful logins still result in inability to scrape/log any order information from time period 02/06/2024-02/26/2024 inclusive for my account. I'm able to scrape data from before and after that time period, and the official Amazon order history shows no discontinuity in the timeline. 

This occurs no matter which time period I request displayed from Amazon (last 30 Days, 2 months, 3 months, etc.), nor which time period I request from the extension (1 mo/2 mo/3mo/2024).

 This issue has only begun to occur since the start of 2024. I'm fully subscribed, and have been so since early 2023. I have access to all premium features from within the extension dialog box. I will be happy to help nail down the bug in any way I can.

I'm currently running the latest version (Version 120.0.6099.234) of the Chrome Browser under Mac OS Ventura V13.6.4 on a late model 2019 MacBook Pro, maxed at 48GB of RAM (so no issues with CPU/Memory), utilizing V1.11.0 of the extension.

Any help would be greatly appreciated!

**Comment by philipmulcahy** [comment]
1) Thanks for trying out the stuff in the readme!2) This is not going to be a subscription/non-subscription thing: the scraping code is unimpacted by that setting.3) Please can you capture a console log of a failed scrape after clearing the cache? There are instructions in the readme about how to turn off log filtering. I wrote a tool to help analyse logs and find “bogey” orders that are crashing the scrape code. If we find such an order, the next task will be to send me some html from one or more such orders: sorry this is going to be a bit messy!Sent from my phoneOn 3 Mar 2024, at 02:03, TrekLurker ***@***.***> wrote:﻿
As the title indicates, and following all debug suggestions (clear cache/cookies), repeated successful logins still result in inability to scrape/log any order information from time period 02/06/2024-02/26/2024 inclusive for my account. I'm able to scrape data from before and after that time period, and the official Amazon order history shows no discontinuity in the timeline.
This occurs no matter which time period I request displayed from Amazon (last 30 Days, 2 months, 3 months, etc.), nor which time period I request from the extension (1 mo/2 mo/3mo/2024).
This issue has only begun to occur since the start of 2024. I'm fully subscribed, and have been so since early 2023. I have access to all premium features from within the extension dialog box. I will be happy to help nail down the bug in any way I can.
I'm currently running the latest version (Version 120.0.6099.234) of the Chrome Browser under Mac OS Ventura V13.6.4 on a late model 2019 MacBook Pro, maxed at 48GB of RAM (so no issues with CPU/Memory), utilizing V1.11.0 of the extension.
Any help would be greatly appreciated!

**Comment by philipmulcahy** [comment]
no response: closing
