### ISSUE TITLE
No years are popping up

### ISSUE THREAD

**Issue by nancyjg22** [philipmulcahy/azad#269]
Hi, your extension sounds like it's exactly what I'm looking for - thank you for creating it!  I've installed, removed and installed it many times on different browsers but it's not showing me anything where I can choose dates. Please tell me what I'm doing incorrectly.
<img width="522" alt="image" src="https://github.com/philipmulcahy/azad/assets/123346614/5a40513f-d536-4b7c-9381-0e71c06227a1">

**Comment by philipmulcahy** [comment]
Nice screenshot! - it shows no year buttons on top of some orders, which answers the first couple of questions I'd have asked otherwise.
Have you tried clicking on the "force logout" button, then logging back into Amazon?
If that doesn't work, then there are two further steps
1) get me a console log from a logged in amazon page: https://github.com/philipmulcahy/azad?tab=readme-ov-file#how-to-save-a-log-file
2) get me the html from this url (assuming you are a .com user): https://www.amazon.com/gp/css/order-history?ref_=nav_AccountFlyout_orders

Yours,

Philip

**Comment by philipmulcahy** [comment]
given astorialic@ has posted #268 (somewhat more hastily) today, and it might be the same thing, I've duped it into this one, and then went and took my .com and .co.uk accounts for a spin on the currently deployed extension version - it's working fine for me, so really hoping this is user error and a coincidence rather than the harbinger of amazon having changed something that kills the extension for everyone until I can get to the bottom of it.

**Comment by philipmulcahy** [comment]
@astorialic, while @nancyjg22++ has implicitly shown she's read the self-help guide which [I ask folks to read](https://github.com/philipmulcahy/azad?tab=readme-ov-file#common-problems-with-some-fixes), you did not - have you seen [this](https://github.com/philipmulcahy/azad?tab=readme-ov-file#no-orange-year-buttons-showing-in-the-extension-popup)?

**Comment by nancyjg22** [comment]
Thanks Philip!

I'll do what you suggest tomorrow when I'm back at my desktop.

You are amazing!!

I'll let you know what happens!  FYI, I'm in the US.

Nancy




-------- Original message --------
From: Philip Mulcahy ***@***.***>
Date: 3/9/24 6:37 PM (GMT-05:00)
To: philipmulcahy/azad ***@***.***>
Cc: Nancy Gilboy ***@***.***>, Author ***@***.***>
Subject: Re: [philipmulcahy/azad] No years are popping up (Issue #269)


Nice screenshot! - it shows no year buttons on top of some orders, which answers the first couple of questions I'd have asked otherwise.
Have you tried clicking on the "force logout" button, then logging back into Amazon?
If that doesn't work, then there are two further steps

  1.  get me a console log from a logged in amazon page: https://github.com/philipmulcahy/azad?tab=readme-ov-file#how-to-save-a-log-file
  2.  get me the html from this url (assuming you are a .com user): https://www.amazon.com/gp/css/order-history?ref_=nav_AccountFlyout_orders

Yours,

Philip

**Comment by philipmulcahy** [comment]
<img width="1110" alt="image" src="https://github.com/philipmulcahy/azad/assets/1668892/b135bb2d-b1a6-42f9-b462-ac3067de39aa">
