### ISSUE TITLE
Bug: Displays wrong data from cache after switching accounts

### ISSUE THREAD

**Issue by jwarkentin** [philipmulcahy/azad#273]
My wife and I have separate accounts and I am signed into both. I was attempting to generate a report of all orders for last year from each of our accounts but ran into this issue.

### Steps to reproduce

- Generate a report for the first account
- Hover over the "Account & Lists" dropdown and click "Switch Accounts" at the bottom. Switch to another account.
- Generate a report for the second account

### Expected result

Should show correct orders for each account

### Actual result

First report generated is correct. Second report shows fewer orders than the first but not the correct orders for the second account. AFAICT it shows the a subset of orders from the first account.

**Comment by philipmulcahy** [comment]
What happens if you clear the cache between the two runs?Sent from my phoneOn 4 Apr 2024, at 09:49, Justin Warkentin ***@***.***> wrote:﻿
My wife and I have separate accounts and I am signed into both. I was attempting to generate a report of all orders for last year from each of our accounts but ran into this issue.
Steps to reproduce

Generate a report for the first account
Hover over the "Account & Lists" dropdown and click "Switch Accounts" at the bottom. Switch to another account.
Generate a report for the second account

Expected result
Should show correct orders for each account
Actual result
First report generated is correct. Second report shows fewer orders than the first but not correct orders for the second account.

**Comment by philipmulcahy** [comment]
If clearing the cache fixes it, I am inclined to close, claiming it is not a bug. We _could_ add the user id to the cache keys, which would make it go away, but it would also cross the rubicon in terms of fetching and holding that identity.
No response in another 2 days => assumption that all is good.

**Comment by philipmulcahy** [comment]
7 days and no response -> closing.
