### ISSUE TITLE
Stopped working in business account

### ISSUE THREAD

**Issue by archetyped** [philipmulcahy/azad#277]
The extension has recently stopped producing any results in [Amazon Business](https://www.amazon.com/business/) accounts.  However, the extension functions normally in standard Amazon accounts.  There are also no year buttons when logged into business account.

All business and standard accounts tested are US-based.

* Extension version: 1.12.0
* Premium subscription active: Yes
* Verbose log: sent via email

## Fixes attempted

* Logged out of Amazon account/logged back in
     * Also tested in private/incognito window
* Browser:
    * Clear cache
    * Clear site data
* Extension:
    * Clear cache option in extension popup
    * Force logout option in extension popup

## Screenshots

Extension popup: No years listed for business account
![Extension popup with no years listed](https://github.com/philipmulcahy/azad/assets/3237917/fd03a15c-c6bb-4557-86b9-8cb96b4e142c)

Extension popup scrape results
![Extension popup scrape results](https://github.com/philipmulcahy/azad/assets/3237917/2359a5f2-cbba-47a2-b9b5-5f79fceb5bdf)

Extension results page: Empty for business account
![Extension results page: Empty for business account](https://github.com/philipmulcahy/azad/assets/3237917/41a90f01-f872-4ec9-99c9-9dded759eb5a)

## Notes

One related factor may be the different request URLs used to display a specific selection of orders in business accounts.

Example - Display orders for 2023:

* Standard: `https://www.amazon.com/your-orders/orders?timeFilter=year-2023`
* Business: `https://www.amazon.com/gp/css/order-history#time/2023/pagination/1/`
    * Using the full order history URL or just URL query from the standard account simply loads the standard "recent orders" results page.

**Comment by philipmulcahy** [comment]
Thanks for reporting!


I wonder if they’ve changed something in the business order list page meaning that we don’t get the list of years any more - that would cripple all the other functionality

The good news: if you can send an email to ***@***.*** ***@***.***> with the html for the order list page for your business account (don’t attach it to this ticket), that offers me a good chance of being able to debug and fix. Please put #277 in the subject so I can tie it back to this ticket.  The URL for my non-business UK account looks like this: https://www.amazon.co.uk/gp/css/order-history  and is accessed from a link entitled “Your Orders”.

The not so good news:  I am saturated at my day job to the point where I’m getting home in the evenings and just slumping into a heap - not much work has been happening on azad for a while.

More good news: I’ve got plans to fix my life in regards to the day job - I will have time to work my way through the backlog before too long.


Yours,

Philip

**Comment by philipmulcahy** [comment]
ok - github isn't being helpful with email addresses is it - it should show azadextension at gmail dot com

**Comment by archetyped** [comment]
HTML source of business account order history page sent via email.

**Comment by haitianboy420** [comment]
i too am having the same issue and would like to track the fix

**Comment by philipmulcahy** [comment]
Hi @archetyped,

The html you sent me renders like this (e.g no actual order data):
<img width="1229" alt="image" src="https://github.com/philipmulcahy/azad/assets/1668892/1cb844ee-a0d9-4dc9-8354-19e678a00ac6">
(The blanking out is on the page, not me preserving your privacy)

1) When you fetched it, did it look like this?
2) If so, then we have our answer: the extension can't see stuff Amazon is not letting _you_ see (because you're not logged in properly or similar)
3) If not (e.g. you could see some orders), then things are about to get a fair bit more interesting. I have some ideas about what to do next, but they're going to be a bit more involved - I think you're going to need to figure out how to save a HAR file for and send it to me in our gmail thread. Outline steps: i) open the relevant amazon orders link ii) open the Developer Tools (three dots button, More tools, Developer tools), iii) Choose the Network tab iv) look for a download arrow somewhere in the control bar, that says Export HAR when you hover over it. v) zip it vi) attach it to an email with 277 somewhere in the subject

I will have to figure out how to extract the data from it (I've never needed to use one before) and then try and understand what Amazon's up to.

**Comment by philipmulcahy** [comment]
1) see updated instructions in previous post (to capture HAR _including_ file contents).
2) I've done my homework on how to handle HAR files - it's gonna be straightforward, so we're in with a chance.

**Comment by archetyped** [comment]
> The html you sent me renders like this (e.g no actual order data)

The HTML source was as provided from the browser's "View Source" command.  As with many websites, Amazon updates the document via JS after loading.  I can provide the post-load rendered HTML if that's what you need instead.

In the meantime, it looks like the main difference on the order history page for business accounts, is that the years are rendered in a different HTML element:

```html
<select name="timeFilterDropdown" autocomplete="off" id="timeFilterDropdown" tabindex="0"
    data-action="a-dropdown-select" class="a-native-dropdown a-declarative">
    <option value="yoLast30Days" id="timeFilterDropdown_yoLast30Days" data-a-id="timeFilterDropdown_yoLast30Days" selected="">Last 30 days</option>
    <option value="yoPast3months" id="timeFilterDropdown_yoPast3months" data-a-id="timeFilterDropdown_yoPast3months">Last 3 months</option>
    <option value="2024" id="timeFilterDropdown_2024" data-a-id="timeFilterDropdown_2024">2024</option>
    <option value="2023" id="timeFilterDropdown_2023" data-a-id="timeFilterDropdown_2023">2023</option>
</select>
```

The [current XPath expression in `extraction.get_years()`](https://github.com/philipmulcahy/azad/blob/master/src/js/extraction.ts#L175) will not find this element due to the different `name` attribute.  Note that the page also contains multiple elements (hidden via CSS) that *do* match the current XPath expression.

Example:

```html
<select name="timeFilter" autocomplete="off" tabindex="0" data-action="a-dropdown-select" class="a-native-dropdown a-declarative">   
    <option value="">Last 30 days</option>
    <option value="">Last 3 months</option>
</select>
```

To exclude these invalid elements, perhaps the XPath expression could be updated to only retrieve `option` elements containing a non-empty `value` attribute:

```xpath
//select[@name="orderFilter" or @name="timeFilter" or @name="timeFilterDropdown"]/option[string-length(@value)!=0]
```

If you can point me in the direction on how to build this extension from source for testing, I can work on a PR if that would help.

**Comment by philipmulcahy** [comment]
Hi @archetyped,

you're right - js does often mutate the html after fetching. Azad works on the pre-mutated html, because 1) it would be very very slow to wait (you cannot easily tell when js has finished doing stuff) for every page it fetches (more than one per order); 2) that js running in each fetched page might make further calls to Amazon that would look like even more a denial of service attack than hitting all the order pages for a year in a few seconds, increasing the chance of you being logged out.

In the current (still working for me, and presumably most other users, since I am not being besieged with complaints) logic, the orders page contains all the available years in the page that's fetched _before_ js runs. I think you're telling me that the years only appear on the business page you're seeing _after_ js runs. Are you absolutely sure about this? It would be very convenient if all we need to do is add a new xpath variant.

I am no expert on HAR files, but I believe they contain the raw fetch data, **so a HAR file would be great.** 
I need a HAR that includes html content: in the chrome developer tools, the right click option for that is labelled "Save all as HAR with content".
Another clean way to get the source is: 
1) open the developer tools on the orders page,
2) then select the "Network" pane
3) refresh/reload the page
4) verify that the order years are visible (e.g. it's not asking you to log in)
you should see a list of each of the document fetches that have gone into showing that page
the first entry is the html file whose url is displayed in the bar at the top of the browser
5) right click on that first entry and it should offer a menu item called Copy -> Copy as cURL
6) in your clipboard should be a fully qualified command for "curl" - a commandline tool for fetching web stuff
7) if you're on a mac or linux then curl should already be installed, on windows you're going to need to do some homework
8) run the cmd and email me the resulting file

Yours,

Philip

**Comment by haitianboy420** [comment]
Would you be willing to do a screen share to gather information to resolve this issue? Zoom, Teams, etc...
id love to get you the information that you are requesting but i am struggling to pull the info. I am using Windows 11 and do not know how to use curl.

**Comment by philipmulcahy** [comment]
Can you please send contact details - email/whatsapp number to azadextension at gmail dot com ***@***.***> (e.g. don’t share them with the internet on this ticket), with #277 somewhere in the subject line and I’ll conjure up some possible dates and times.

Yours,

Philip

**Comment by haitianboy420** [comment]
sent

**Comment by philipmulcahy** [comment]
pitched call on Monday July 29th

**Comment by haitianboy420** [comment]
Sure, what time?

**Comment by philipmulcahy** [comment]
20:00 my time?Sent from my phoneOn 22 Jul 2024, at 18:01, haitianboy420 ***@***.***> wrote:﻿
Sure, what time?



On Mon, Jul 22, 2024 at 12:41 PM Philip Mulcahy ***@***.***>

wrote:

**Comment by philipmulcahy** [comment]
Check your email just before for a call linkSent from my phoneOn 26 Jul 2024, at 19:38, Philip Mulcahy ***@***.***> wrote:﻿20:00 my time?Sent from my phoneOn 22 Jul 2024, at 18:01, haitianboy420 ***@***.***> wrote:﻿
Sure, what time?



On Mon, Jul 22, 2024 at 12:41 PM Philip Mulcahy ***@***.***>

wrote:

**Comment by philipmulcahy** [comment]
no show from @haitianboy420  - let's try another day

**Comment by haitianboy420** [comment]
I am so sorry. I am in the hospital. I tore my ACL last night.

**Comment by philipmulcahy** [comment]
I've done that before playing squash - it hurts!
