### ISSUE TITLE
Gap in order data

### ISSUE THREAD

**Issue by etheric42** [philipmulcahy/azad#278]
For several months I've been having a gap in my order history data.  The gap varies in length from 1-3 months.  The current month or 30 days is always displayed, but then there's a 1-3 month gap where no order history is found even though there is order history in Amazon, then the order history resumes as if nothing is wrong.

For example, if I use the extension to scrape all 2024 orders, I get all of May, then no orders until January 30.  This has persisted since at least December.

I am on version 1.12.0

(p.s. love the extension, been using it for a long time!)

**Comment by philipmulcahy** [comment]
Interesting. Can you share a console log of such a scrape please? Does clearing the extension’s cache fix it?Sent from my phoneOn 22 May 2024, at 03:45, etheric42 ***@***.***> wrote:﻿
For several months I've been having a gap in my order history data.  The gap varies in length from 1-3 months.  The current month or 30 days is always displayed, but then there's a 1-3 month gap where no order history is found even though there is order history in Amazon, then the order history resumes as if nothing is wrong.
For example, if I use the extension to scrape all 2024 orders, I get all of May, then no orders until January 30.  This has persisted since at least December.
I am on version 1.12.0
(p.s. love the extension, been using it for a long time!)

**Comment by philipmulcahy** [comment]
I'll leave this open until mid-june and then close as "fired and forgotten" unless I see a response to my questions.

**Comment by etheric42** [comment]
Was out of the house for an extended time.  Thanks for your patience.

Clear cache did not resolve it previously.  But it seems to be working now. (?)  Feel free to close and I'll reopen it when I run my books next month again if it comes up.
