### ISSUE TITLE
Add-on for Firefox?

### ISSUE THREAD

**Issue by blacktemplar** [philipmulcahy/azad#30]
I don't know how difficult/ how much work this is, but could we also turn this into a firefox Add-on?

**Comment by philipmulcahy** [comment]
Converting: apparently easy - to the extent that some of the chrome apis with chrome in their name "just work" in FF - I tested this out because there are a bunch of FF users at work that want me to release an internal chrome extension tool I wrote in FF guise.

Releasing: not quite so much - and much of the pain is recurrent - as I understand it FF want one of "their" people to review the code for every drop.

To add salt to the wound, having a private install is a pain in the backside - you have to enable them each and every time you start FF.
