### ISSUE TITLE
FYI: Page navigation links issue

### ISSUE THREAD

**Issue by ScottMcNay** [philipmulcahy/azad#43]
Using Amazon.com on Windows 10
Today, when I reviewed the extension for issues and possible enhancements, I noticed, after selecting 2019 and viewing All, that the page navigation links did not have spaces: "Previous1Next".

Unfortunately, though, I don't seem to be able to reproduce. :-( When I try to reproduce, the "1' is formatted as a button, not a link.

BTW, what's the difference between "data table" view with "All" selected, and "plain table"?

**Comment by philipmulcahy** [comment]
Difference between datatable and plain table: data table is sortable and filterable even when only some of the data is visible. The plain table doesn't sort and it shows all the years stuff in one go - this can challenge some browsers and can involve a lot of scrolling.
For me, the plain table is only useful when I'm debugging my use of datatable (magic javascript that is way over my head). I think some people use plugins that can extract bulk data from plain tables straight into spreadsheets, but that's not why I've kept it.

is this still happening in 1.8.26?
I am going to prioritise making it easy for users to capture diagnostics, because some of the problems you're reporting are really hard to reproduce when I don't have access to that users' account and country.
If this were a business that was making money, we could just set up accounts in every amazon region and buy stuff periodically and use the accounts for testing. Given this is a spare time project for me, that isn't going to happen.

**Comment by ScottMcNay** [comment]
No, I think that was a one-shot; might have been the result of image files not being fetched.

Sorry, didn't notice the filter/sort on datatable.

I use copy-n-paste(value) to copy from plain tables to a spreadsheet.

I turned on the error reporting, and my extension reports errors; I've attached.
[www.amazon.com-1569645029491.log](https://github.com/philipmulcahy/azad/files/3665093/www.amazon.com-1569645029491.log)

Also, I went through the report and identified every issue I saw; I'm attaching that as well.
[amazon_order_history_20190927 sample.xlsx](https://github.com/philipmulcahy/azad/files/3665149/amazon_order_history_20190927.sample.xlsx)

Let me know if you need page HTML.

BTW, looking at reviews, I see someone asking how to get sums; I discovered a few months ago that you can put formulas into a CSV and Excel will calculate. This works for me:
SumTest.csv:
1
2
3
=sum(A1:A3)

**Comment by ScottMcNay** [comment]
I update the sample to a template; follow the instructions given.

[amazon_order_history_20190928 template.xlsx](https://github.com/philipmulcahy/azad/files/3665967/amazon_order_history_20190928.template.xlsx)

**Comment by ScottMcNay** [comment]
@philipmulcahy, see what you think of having the extension export the attached as part of the CSV file. Note that "4" will need to be replaced by the current row #, and "6" with the row # of the last row of data. I'm not familiar with working with extensions, else I'd try updating the code myself.
[amazon_order_history_20190928 csv template.txt](https://github.com/philipmulcahy/azad/files/3666001/amazon_order_history_20190928.csv.template.txt)
