### ISSUE TITLE
Export to CSV - small niggle

### ISSUE THREAD

**Issue by JonSilver** [philipmulcahy/azad#8]
When exporting, prices are exported with their currency symbol, so they're imported to the spreadsheet by default as strings rather than numbers. Whilst it's possible to remove these en masse in a spreadsheet like Excel, it's an extra step that needs to be done. Any chance of stripping these during export?

**Comment by philipmulcahy** [comment]
I'm cautious about this... is it possible that one CSV might need to contain more than one currency?

**Comment by JonSilver** [comment]
I didn’t think that was possible on Amazon. If it is, the currency could be stripped from each value and inserted into a separate adjacent column. That would still have the desired effect whilst preserving fidelity.

**Comment by philipmulcahy** [comment]
OK - I'll leave this issue open until it's done or we think of something better

**Comment by blacktemplar** [comment]
Maybe worth an own issue, but it is related so I post it here to discuss. I needed quite some time until I was able to use the date column for sorting etc. I had to parse the date string in my office file, maybe it would be easier to include in javascript some date parsing so that when exporting to csv it uses a date format every office suite can recognize? (YYYY-MM-DD?)

**Comment by philipmulcahy** [comment]
iso8601 is my goal, but the problem is different countries have different formats and I don’t have access to orders on most of the amazon sites.
Currently I’m planning to try something out with a generic parser that falls back to the amazon provided date format if it cannot parse. I need to choose the library. Date.parse is definitely not gonna fly.
There’s already a ticket for it - still open.

**Comment by blacktemplar** [comment]
Ah ok, I also did some thinking about the discussion above about currencies. I think the best would be to move the currency into the column header and if there is more than one currency in a column we cuplicate the column for each currency, so at the end we have for every currency occuring one column. This would also make sense if we want to sum up in a meaningful sense, so we could also use this solution not only in the csv export but also in the result table. This would also solve many more complicated cases. For example I don't know if that can happen but it solves also the problem if I pay for the product itself in Euro and for the shipment in Dollar, or even worse I pay the shipment in two parts, first part into the US in Dollar and second part in Europe in Euro ^^.

**Comment by philipmulcahy** [comment]
on dates: I couldn't find the ticket so I cut this one: https://github.com/philipmulcahy/azad/issues/31
let's move date discussions there.

**Comment by ScottMcNay** [comment]
Amazon (and PayPal) implement this with a currency column, such as "USD", "CAD", and "GBP". See:
https://www.amazon.com/gp/b2b/reports
https://business.paypal.com/merchantdata/consumerHome
https://history.paypal.com/us/cgi-bin/webscr?cmd=_history
I still want to know how much it is in MY currency since that's what's taken out of my account.
