### ISSUE TITLE
No 2019 output

### ISSUE THREAD

**Issue by jimdeane** [philipmulcahy/azad#86]
I got correct output for all years back to 2002 but nothing was produced for 2019. no error was produced and the dialog box showed items being generated but not output page was produced.

**Comment by philipmulcahy** [comment]
that doesn’t sound good - are you able to attach the debug console log for a 2019 run  to this ticket?

**Comment by jimdeane** [comment]
attached the console log and a video
[www.amazon.co.uk-1573415052994.log](https://github.com/philipmulcahy/azad/files/3828917/www.amazon.co.uk-1573415052994.log)

 capture of the process at https://www.dropbox.com/s/c9r5q2x8gkevzg6/Your%20Orders%20-%20Google%20Chrome%202019-11-10%2019-46-47.mp4?dl=0

**Comment by alex-warner** [comment]
I have a similar issue, sometimes 2018 works, but usually it just scans everything, no errors, but no output page. Below is the debug for the one time 2018 worked.

[Amazon order history debug info.txt](https://github.com/philipmulcahy/azad/files/3833756/Amazon.order.history.debug.info.txt)

**Comment by philipmulcahy** [comment]
@Alex Warner: A log from a failing case is probably going to be more useful.
Fair warning: it’s going to be a while before I’m in a position to look at this bug - sorry!

**Comment by alex-warner** [comment]
Thanks Philip, I'll check in later.

**Comment by mikebk824** [comment]
I have had the same problem with amazon.com. I found that the result table didn't display for 2019 but did for 2018. 

I tried to copy the console log but had difficulties. When I shift clicked to select the whole log, I found it was only displaying the last few lines.  As I kept trying unsuccessfully to get the whole log, suddenly the table displayed and has continued to display.

I noticed that even while it was displaying the table, the console had 1 error, a 404 error:
empty.gif:1 GET https://smile.amazon.com/empty.gif?1574364737656 404
Image (async)

**Comment by philipmulcahy** [comment]
I have managed to get this to happen on my dev rig - I will report back when I figure out more. Sorry for delay.

**Comment by philipmulcahy** [comment]
@jimdeane @alex-warner @mikebk824
I think I know what's going on...

Short version: use the clear cache button as a work-around (and then hit 2019).

Long version: I think it's getting confused by inconsistency between the cached final list page and the expected order count if you've ordered more stuff since the cache was built. I reckon that a proper fix could involve either:

1) ignoring the cache for the newest year if the count has changed (we'd need to cache the count so we could see if the count had changed - at the moment that's pretty much the only query that doesn't get cached, and we'd also need to label cache rows with their year somehow - more complexity)

2) like Fermat, I've got a great idea, but there's not enough room to write it down here... (not really - I'm just a bit tired and want to think about this option a bit more before writing it down).

Meanwhile, I've improved logging in the unittests3 branch which I will merge to master and push in the next few days. This should help with debugging if the workaround doesn't work (though I'm quietly confident it is caused by new orders and the cache colliding - no-one's complaining about consistent failures for years other than 2019. (@alex-warner - have I misunderstood?)

Yours,

Philip

**Comment by bb1bsc** [comment]
Seems i have the same problem, 2019, The workaround in question does not seem to work,
1) Click Clear Cache
2) Pop up dialog appears to confirm cache cleared
3) Click Extension icon again as the 2019 selection window has closed and select 2019

Am i doing something wrong ?

**Comment by philipmulcahy** [comment]
I have just pushed v1.9.2 that might fix this (should be with you within an hour). Please post feedback on this bug (good or bad) here.
Thanks!

**Comment by philipmulcahy** [comment]
If it does work and you're feeling pleased: https://www.justgiving.com/fundraising/azad-pah

**Comment by bb1bsc** [comment]
Hi Its working, Thanks ever so much
