### ISSUE TITLE
Logs out and cant resume - large history

### ISSUE THREAD

**Issue by teddy6565** [philipmulcahy/azad#96]
I have a large history I am trying to download. It is over 2500 orders in any year. Everything work well but then gets to about 2000 and it says logged out. I am actually not convinved it is logged out as broswer still open. I am even keeping alive manually by navigating amazon. Then I am unable to resume, it restarts all over again if I click on the year. Thanks

**Comment by philipmulcahy** [comment]
I think this might be Amazon logging you out (perhaps partially). They can’t close your browser, just stop responding with good data. There seem to be different types of URLs (for example details on digital orders) that are served from particular services inside Amazon, and I suspect that these services have different DOS protection settings, without telling the other parts of the site that they’ve logged you out.

Obviously we can’t change Amazon’s behaviour but azad does have a workaround:
When the extension queries a URL, it caches the response, so if you get logged out, you just restart the year (don’t try “all years” if you have thousands of orders per year!). It will not hit Amazon for the URLs it has cached, and so whizz through all the ones it already has and go to work on the ones it doesn’t.

The limit will come when someone has more orders in a year than can fit in the cache. No-one’s reported this yet. Two approaches suggest themselves if this happens 1) data compression/reduction in the cache and 2) reporting months or quarters rather than years.
Let me know how you get on with “retrying”.

Yours,

Philip

**Comment by philipmulcahy** [comment]
@ScottMcNay pointed out that we removed the "All Years" button a while back so please disregard my exhortations to ignore it! (Thanks Scott!)

**Comment by ScottMcNay** [comment]
@teddy6565, of the 2500, how many of those are digital orders and how many are physical orders? Do you have "keep me signed in" enabled?

**Comment by teddy6565** [comment]
Hi I am sory for later reply, I have been trying this again. However I still cant get a full download. There seem to be a few issues. First the cache doesnt always work, it keeps resetting back to 0 once loggin out, evern after trying same year. After many attempts I got a full 5800 items to complete, but I couldnt download the csv as it would just freeze within chrome as presumably the file was too big. So I am afraid to say I am still now any further forward:(

**Comment by philipmulcahy** [comment]
This must be a real pain for you @teddy6565 - sorry!
I can think of two alternative steps to take next...
1) share your account details with me so I can drive your account.
2) get a console log and attach it to this ticket (see the [home/help page])(https://github.com/philipmulcahy/azad/blob/master/README.md): 

DON'T DO (1) without coordinating with me first - I don't want to have it a minute longer than necessary, and it'll be a while before I've got time.

While 1) would probably be faster, you don't know me and I think we should try (2) first. If we can't figure out what's happening immediately, I could send you special versions that add more verbose logging to home in on the problem.

Yours,

Philip

p.s. @ScottMcNay 's idea was good - thanks Scott!

**Comment by philipmulcahy** [comment]
no response from user: closing
